### ISSUE TITLE
Feature Request: Focused Mode Processing

### ISSUE THREAD

**Issue by ElTimuro** [elie222/inbox-zero#10]
Going though Mails sorting, archiving and replying should be done in focused bursts.
 
I would love a "Sort Now" Button, that gives you a focused view on you open mails:

- one Mail at a time
- reply, archive, Mark todo or set reminder for later to move to next (maybe also a suggested action of the above with their own shortcut)
- keyboard commands for the above 
- nothing else visible in UI

**Comment by elie222** [comment]
Hey, sorry for late reply here. Just seeing this. Great suggestion.

**Comment by elie222** [comment]
Labelled as feature request. Can also make requests here: https://www.getinboxzero.com/feature-requests
