### ISSUE TITLE
Batched Mails

### ISSUE THREAD

**Issue by ElTimuro** [elie222/inbox-zero#11]
Feature Idea

- "Receiving" Mails only on predetermined times of the day e.g. 9 am and 16 pm
- Mails are still there and accessible but Hidden until process window arrives

**Comment by elie222** [comment]
So if a user has 100 emails in their inbox from a week ago, when they log in they'll still see those? But won't see the current batch till the time passes?

**Comment by elie222** [comment]
Labelled as feature request. Can also make requests here: https://www.getinboxzero.com/feature-requests
