### ISSUE TITLE
Refactor Readme file

### ISSUE THREAD

**Issue by Ipriyankrajai** [elie222/inbox-zero#127]
As we configured Redis locally we should remove `UPSTASH_REDIS_URL` from The required environment variables in [Readme file](https://github.com/elie222/inbox-zero/blob/main/README.md)

![image](https://github.com/elie222/inbox-zero/assets/32142351/b66835d1-6617-4e24-8a13-549faacf7730)

**Comment by elie222** [comment]
So this is actually needed for self hosters. And the db url. So I don't want to fully delete this. It's only when using the Docker Compose that you don't need it.
