### ISSUE TITLE
Remove unused AI commands from Compose

### ISSUE THREAD

**Issue by elie222** [elie222/inbox-zero#133]
Novel had a recent update to make this easier: https://novel.sh/docs/guides/tailwind/slash-command

We don't want to show:

* Give Feedback
* Add image (or fix image sending so it works)

**Comment by rohitt-gupta** [comment]
hi, i would love to work on this issue, please assign me

**Comment by elie222** [comment]
> hi, i would love to work on this issue, please assign me

Done!

**Comment by elie222** [comment]
For this one, update Novel to v2:
https://novel.sh/docs/quickstart
