### ISSUE TITLE
Mobile Navigation Does not close after clicking on the link

### ISSUE THREAD

**Issue by rohitt-gupta** [elie222/inbox-zero#134]
Steps to reproduce:
1. Visit the mobile version of the inbox-zero landing page.
2. Click the three lines/menu icon on the top right.
3. Navigate to any of the mentioned links (Eg, FAQ).
4. Observe

Actual: - After navigating/redirecting the menu should close
Expected- After redirecting./ navigation it should the menu should close.

**Comment by elie222** [comment]
Closed by https://github.com/elie222/inbox-zero/pull/135
