### ISSUE TITLE
Discord links are dead

### ISSUE THREAD

**Issue by TheMarf** [elie222/inbox-zero#146]
While not technically an app issue....wanted to join the discord to read up on self hosting.

**Comment by elie222** [comment]
Thanks. Here you go: https://discord.gg/hWUZ7bWuW5

**Comment by elie222** [comment]
This seems to work:
https://getinboxzero.com/discord
https://discord.gg/UnBwsydrug

Where did you find the broken link?

**Comment by TheMarf** [comment]
Both lead me to the following
![image](https://github.com/elie222/inbox-zero/assets/19783744/7435114f-93e7-4584-91f0-9f90b0c16b94)

**Comment by TheMarf** [comment]
Fixed, signed out of everything in the browser and cleared cache/cookies then it worked.

**Comment by elie222** [comment]
> Fixed, signed out of everything in the browser and cleared cache/cookies then it worked.

Weird. Glad it's working now
