### ISSUE TITLE
Bug? Unsubcribe mode for some users not working on mobile?

### ISSUE THREAD

**Issue by elie222** [elie222/inbox-zero#160]
I've found this hard to reproduce. But it does happen on some devices. This is from a few months ago:
![image](https://github.com/elie222/inbox-zero/assets/3090527/eab7ec11-8c1c-46cc-94df-306cbb8844dc)

**Comment by prynsh** [comment]
Hello sir, can you please elaborate the issue a little bit more?
Thank you.

**Comment by elie222** [comment]
> Hello sir, can you please elaborate the issue a little bit more? Thank you.

Not sure this is still relevant as I made adjustments to mobile. Closing the issue
