### ISSUE TITLE
FR: Dockerized version of app?

### ISSUE THREAD

**Issue by DarkPhyber-hg** [elie222/inbox-zero#177]
Would love to see a docker compose file and .env file that i could just setup to have a fully running environment.

**Comment by elie222** [comment]
> Would love to see a docker compose file and .env file that i could just setup to have a fully running environment.

Hey, the project has a Docker Compose and sample .env file. What are you after in addition?

**Comment by 0xrushi** [comment]
@elie222 I think the docker compose is only for the postgres and redis and not for frontend

**Comment by 0xrushi** [comment]
Added one https://github.com/elie222/inbox-zero/pull/198 :)
