### ISSUE TITLE
docker support?

### ISSUE THREAD

**Issue by uhlhosting** [elie222/inbox-zero#18]
hi, 

any plans to add docker support?

**Comment by elie222** [comment]
Hey,
That would be a good addition and make it a lot easier for newcomers to run.
Will try get to it this week 🙏

**Comment by elie222** [comment]
So I've improved the README on how to get started:
https://github.com/elie222/inbox-zero#getting-started-for-developers

PRs for a Docker Compose are welcome.

**Comment by zxt-tzx** [comment]
should be closed by https://github.com/elie222/inbox-zero/pull/36!
