### ISSUE TITLE
Largest items in inbox - Size is NaN

### ISSUE THREAD

**Issue by buneeIsSlo** [elie222/inbox-zero#182]
Under the **What are the largest items in your inbox?** section, the size for every email is being displayed as `NaN MB`.

![inbox0](https://github.com/elie222/inbox-zero/assets/79749200/08fecfe3-f6e1-4360-baee-3fc6daf176dd)

**Comment by madhav-relish** [comment]
Hey @elie222 , I'd like to work on this, can you assign this to me!
