### ISSUE TITLE
support local AI model

### ISSUE THREAD

**Issue by mikestaub** [elie222/inbox-zero#190]
I want to use my ollama server on my laptop instead of sending data to OpenAI

**Comment by iydebu** [comment]
yes bro it more safe then if it run in the local server

**Comment by el-shivam** [comment]
This is much needed.

**Comment by elie222** [comment]
This should be quite an easy update. Good first issue for someone to take.
Docs to add it:
https://sdk.vercel.ai/providers/community-providers/ollama
