### ISSUE TITLE
Active class for sidebar 

### ISSUE THREAD

**Issue by Vishvsalvi** [elie222/inbox-zero#201]
![image](https://github.com/user-attachments/assets/08fc4876-d5db-4a62-b152-6279fb7a5456)

The hover effect should stay on the sidebar link if the user is currently on that page.

**Comment by elie222** [comment]
Feel free to take this one!

**Comment by Vishvsalvi** [comment]
Sure, please assign it.

**Comment by Naitik2408** [comment]
Can you explain the issue in more detail. Please provide :
1. The path of the issue page.
2. A video which show the exact issue.
3. Code file which contains the issue(optional, only if you know about this).

**Comment by Vishvsalvi** [comment]
@elie222 #202 resolves this issue. Please have a look at it and close it
