### ISSUE TITLE
Complete this PR: Add functionality for items in Smart Categories dropdown

### ISSUE THREAD

**Issue by elie222** [elie222/inbox-zero#261]
Add functionality for the unimplemented items in this dropdown
https://github.com/elie222/inbox-zero/pull/256/files

Similar functionality already exists in other parts of the app.

**Comment by yashsharma999** [comment]
Hey, I would like to work on this issue.

**Comment by elie222** [comment]
Hey, it's been handled via this in the end:
https://github.com/elie222/inbox-zero/pull/275

Simpler solution that works with existing features.
