### ISSUE TITLE
Ability to delete mails from "largest items in your inbox" (analytics page)

### ISSUE THREAD

**Issue by spaceemotion** [elie222/inbox-zero#49]
I really like the "largest mails" table - but I noticed that most of them are actually spam mails with dubious attachments. I don't want to open them in Gmail directly, so a delete button would be great, too!

**Comment by elie222** [comment]
Great suggestion!

**Comment by ketanMehtaa** [comment]
Can I pick this one up?

**Comment by elie222** [comment]
> Can I pick this one up?

Yes!
