### ISSUE TITLE
Store data in browser with Indexeddb

### ISSUE THREAD

**Issue by elie222** [elie222/inbox-zero#54]
We can store gigabytes of data in an indexddb in the browser.
Use `idb` package to do this.

The advantage here is extra privacy for users. After this is done we can remove large parts of the backend. The client can load the data itself and use the Gmail API to archive/label/reply.
It will also mean faster loading times.

The core tables to use are:
* Emails
* Labels

We may need more tables after for sorting in different ways, or to help with analytics.

**Comment by sharma-shanu** [comment]
@elie222 , Can you assign this task to me ?

**Comment by elie222** [comment]
Not relevant atm.
