### ISSUE TITLE
AI automation names

### ISSUE THREAD

**Issue by dstoutamire** [elie222/inbox-zero#60]
Although AI automation text fields have names, the names don't appear next to the text boxes.  Names also can't be edited; for example, there could be a field in the edit popup when clicking the pencil icon.

**Comment by elie222** [comment]
> Names also can't be edited;

Do you mean like so (this appears when clicking the edit icon):
![CleanShot 2023-12-30 at 21 28 23@2x](https://github.com/elie222/inbox-zero/assets/3090527/3bd0e34a-4f04-4239-8917-d520b87972a2)

But thank you for bringing this up. I agree the UX isn't the best here.
We should maybe show the name even before opening the modal.

**Comment by dstoutamire** [comment]
That seems pretty obvious now that you've shown it to me.
