### ISSUE TITLE
Oath Screen

### ISSUE THREAD

**Issue by davtin19** [elie222/inbox-zero#70]
Once I input the correct URI in google cloud services everything works normal until i try to sign in because after i click sign in on my acc it shows as succesful but then brings me to this consent screen, and then says mismtached uri even tho I KNOW the URI is correct and i dont have any other projects

**Comment by elie222** [comment]
> Once I input the correct URI in google cloud services everything works normal until i try to sign in because after i click sign in on my acc it shows as succesful but then brings me to this consent screen, and then says mismtached uri even tho I KNOW the URI is correct and i dont have any other projects

You mean when setting it up locally, right?

Either your env is wrong or the settings you've put in the Google console. I'm guessing the latter.

**Comment by davtin19** [comment]
Yeah set it up locally but it goes 404 not page found after the verification screen

**Comment by davtin19** [comment]
This helped

Thank you
