### ISSUE TITLE
Mark emails as read

### ISSUE THREAD

**Issue by elie222** [elie222/inbox-zero#81]
- [x] Mark an email when it's read
- [ ] Ability to mark an email as unread

**Comment by elie222** [comment]
`UNREAD` label:
https://developers.google.com/gmail/api/guides/labels
https://developers.google.com/gmail/api/reference/rest/v1/users.messages/modify

See labelling in:
`apps/web/utils/gmail/label.ts`
Can add a function to this file: `markRead(read: boolean)`

In Gmail, messages receive labels. When a thread receives a label it's like applying it to every message in the thread.

**Comment by ThisIsRahmat** [comment]
Hi @elie222 can I work on this?

**Comment by elie222** [comment]
> Hi @elie222 can I work on this?

Hey, I missed this. It's been half done now. The other part is marking as unread. Although probably better to take a different issue. I'll probably add this myself soon.
